### ISSUE TITLE
Competition research

### ISSUE THREAD

**Issue by goodsolution** [goodsolution/developer#1]
Please paste links to comptetitiors

**Comment by michalswig** [comment]
Developer

https://portpraski.pl/
Developer
	Osiedle
		Mieszkanie
		-powierzchnia:255.43 m²
		-liczba pokoi:2
		-piętro:7
		-status:Wolne
		-cechy dodatkowe:Taras
		-cena za m2
		Lokal Usługowy
		-powierzchnia:91.64 m²
		-liczba pokoi:1
		-piętro:0
		-status:Wolne

https://www.domd.pl
Developer
	Miasto
	Osiedle
	-stan:Gotowe|W budowie|W przygotowaniu
	-lokalizacja:Dzielnia1|Dzielnica2|Dzielnia3
		Mieszkanie
		-metraż 
		-piętro
		-liczba pokoi:2
		-cechy dodatkowe BALKON|TARAS|LOGGIA|OGRÓDEK
		-oznaczone jako Oferty Specjalne|Już gotowe|Wykończone|Bliski termin oddania|Ostatnie mieszkania|w konkretnym budynku inwestycji
		-termin realizacji Q4 2024
		-cena za m2

https://rohe.pl/
Developer
	Osiedle
		Mieszkanie
		-budynek na osiedlu
		-metraż
		-piętro:2
		-liczba pokoi:2
		-numer lokalu
		-status:WOLNE|SPRZEDANE
		-karta mieszkania

https://pieknawarka.pl/
Developer
	Dom
	Budynek mieszkalno-usługowy
	-mieszkanie

https://www.yit.pl/
Developer
	Kraj
		Miasto
			Osiedle
				Budynek
					Mieszkanie
					-metraż
					-liczba pokoi
					-cena
					-typ mieszkania
					-piętro
					-cena za mieszkanie
					-zarezerwuj
					-rzut mieszkania

https://www.archicom.pl/
Developer
	Osiedle
		Mieszkanie
		-nazwa inwestycji
		-liczba pokoi
		-cena za mieszkanie
		-promocja
		-gotowe w ciągu roku


https://www.kombinatbud.com.pl/
Developer
	Nieruchomość
	-mieszkanie
	-lokal
	-garaż
		Inwestycja
		-nazwa inwestycji
			Mieszkanie			
			-lokalizacja:	42 Pułku Piechoty budynek 4
			-cena:	429 700 PLN
			-rodzaj:	Mieszkanie
			-status:	Dostępne
			-piętro:	Piętro II
			-pokoje:	3
			-metraż:	55,09 m²
			-odbiór mieszkań: do 31.08.2023

https://oazamokotow.pl/
Developer
	Budynek
		Piętro
			Mieszkanie
			-rzut lokalu	
			-numer
			-piętro
			-metraż [m²]	
			-pokoje	
			-balkon [m²]	
			-taras [m²]	
			-segment	
			-status	
			-schowek	
			-cena

https://murapol.pl/		
Developer
	Województwo
		Miasto
			Miasto1
			Miasto2
				Osiedle
				osiedle1
				osiedle2City city
					Typ Nieruchomości
						Mieszkanie
					v	-powierzchnia
					v	-ilośc pokoi 
					v	-czy dostępny
					v	-rzut lokalu
						-plan lokalu
						-wirtualny spacer 3D
						-widok elewacji
						-plan 3D
						-widok z okna
						-lokal usługowy
					Status
						Oferta specjalna
						Gotowe do odbioru
					Inwestycja
						Nazwa1
						-adres
					Ekspozycja
						Północ
						Południe
						Wschód
						Zachód
					Dodatkowe Atrybuty
						-balkon
						-ogródek
						-taras
					Powierzchnia
						-m2
					Cena
						-cena total

https://krakdevelopment.pl/
Developer
	Budynek
		Lokal
				-typ(mieszkaniowy lub inny)
				-numer
				-piętro
				-metraż
				-broszura do pobrania
