### ISSUE TITLE
Design database

### ISSUE THREAD

**Issue by goodsolution** [goodsolution/developer#3]
Dod:
- make sql script

**Comment by michalswig** [comment]
DB details

 type --->
     apartment
     commercial_unit

 technical status --->
     is_available             tinyint,
     is_during_construction   tinyint,
     is_during_preparation    tinyint,

 sales status --->
     is_ready_to_pick_up               tinyint,
     is_ready_to_pick_up_special_offer tinyint,
     is_reserved                       tinyint,
     is_sold                           tinyint,

**Comment by michalswig** [comment]
TODO
fill real data
sql queries that could be possible on compset pattern - queries.sql file - paste to DB folder

**Comment by michalswig** [comment]
sales_status = 'available'; - use shorts - 'a' , exposure, type
use Dictionary to expand 'a' -'available'
